# Generated by Django 5.2.9 on 2026-02-19 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_user_publisher_profile_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('reader', 'journalist'), ('reader', 'publisher')},
        ),
    ]
