# Generated by Django 5.2.9 on 2026-02-19 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_subscription_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editor_followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
