# Generated by Django 5.2.9 on 2026-02-20 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
    ]
